#imports

import os
import time
from time import sleep

#colors

class color:
    purple = '\033[95m'
    white = '\33[0m'
    orange = '\033[93m'
    red = '\33[91m'
    blue = '\033[94m'
    green = '\033[92m'

def EXIT1():
    os.system('clear')
    print(color.blue + "HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print("HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print("HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print("HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print(color.blue + "HHHHHHHHHHHHHHHHHHHHHHH" + color.green + "888888888888888888888" + color.blue + "HHHHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print(color.blue + "HHHHHHHHHHHHHHHHHHHHHHH" + color.green + "888888888888888888888" + color.blue + "HHHHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print(color.blue + "HHHHHHHHHHHHHHHHHHHHHHH" + color.green + "888888888888888888888" + color.blue + "HHHHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print(color.blue + "HHHHHHHHHHHHHHHHHHHHHHH" + color.green + "888888888888888888888" + color.blue + "HHHHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print(color.blue + "HHHHHHHHHHHHHHHHHHHHHHH" + color.green + "888888888888888888888" + color.blue + "HHHHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print(color.blue + "HHHHHHHHHHHHHHHHHHHHHHH" + color.green + "888888888888888888888" + color.blue + "HHHHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print(color.blue + "HHHHHHHHHHHHHHHHHHHHHHH" + color.green + "88888888888888888" + color.blue + "00" + color.green + "88" + color.blue + "HHHHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print(color.blue + "HHHHHHHHHHHHHHHHHHHHHHH" + color.green + "88888888888888888" + color.blue + "00" + color.green + "88" + color.blue + "HHHHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print(color.blue + "HHHHHHHHHHHHHHHHHHHHHHH" + color.green + "888888888888888888888" + color.blue + "HHHHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print(color.blue + "HHHHHHHHHHHHHHHHHHHHHHH" + color.green + "888888888888888888888" + color.blue + "HHHHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print(color.blue + "HHHHHHHHHHHHHHHHHHHHHHH" + color.green + "888888888888888888888" + color.blue + "HHHHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print(color.blue + "HHHHHHHHHHHHHHHHHHHHHHH" + color.green + "888888888888888888888" + color.blue + "HHHHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print(color.blue + "HHHHHHHHHHHHHHHHHHHHHHH" + color.green + "888888888888888888888" + color.blue + "HHHHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print(color.blue + "HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    start = input("PRESS ENTER TO EXIT")
    time.sleep(0.4)
    BOX()

def BOX():
    os.system('clear')
    time.sleep(0.1)
    print("   H    H     H    H    H    H    H     H    H     H    H    H    H")
    time.sleep(0.1)
    print("H     H    H    H    H    H     H     H    H    H     H    H    H  ")
    time.sleep(0.1)
    print("  ()                                                      ()       ")
    time.sleep(0.1)
    print(" (  )                                                    (  )")
    time.sleep(0.1)
    print("(    )                                                  (    )")
    time.sleep(0.1)
    print("------                                                  ------")
    time.sleep(0.1)
    print("  ||                                                      ||")
    time.sleep(0.1)
    print(" (_)                                                      (_)")
    time.sleep(0.1)
    print("                       (00000000000000000)")
    time.sleep(0.1)
    print("                      (0  0  0  0  0  0  0)")
    time.sleep(0.1)
    print("                     (0  0  0  0  0  0  0 0)")
    time.sleep(0.1)
    print("                    (H----------------------H)")
    time.sleep(0.1)
    print("                   /(0  0  0  0  0  0  0  0 0)\ ")
    time.sleep(0.1)
    print("                  | (0  0  0  0  0  0  0  0 0) |")
    time.sleep(0.1)
    print("                  | (0  0  0  0  0  0  0  0 0) |")
    time.sleep(0.1)
    print("                  | (H----------------------H) |")
    time.sleep(0.1)
    print("                  |  (0 0  0  0  0  0  0  0 )  |")
    time.sleep(0.1)
    print("                  |   (0  0  0  0  0  0  0)    |")
    time.sleep(0.1)
    print("                  |____(00000000000000000)_____|")
    time.sleep(0.1)
    print("HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print()
    print("DO YOU WANT TO EXIT AND GO OUT FROM HERE? OR, YOU WANT STAY?")
    time.sleep(0.1)
    print("STAY")
    time.sleep(0.1)
    print("TAKE THE BOX FROM MY WAY")
    time.sleep(0.1)
    print()
    choose = input("CHOOSE YOUR OPTION(BY TYPING):")
    time.sleep(0.4)

    if choose == "STAY":
        STAY()
    elif choose == "TAKE THE BOX FROM MY WAY":
        TAKE_THE_BOX_FROM_MY_WAY()
    else:
        os.system('clear')
        print("YOU TIPED WRONG OPTION, PLEASE TRY AGAIN!")
        time.sleep(2)
        BOX()

def TAKE_THE_BOX_FROM_MY_WAY():
    os.system('clear')
    time.sleep(0.1)
    print("   H    H     H    H    H    H    H     H    H     H    H    H    H")
    time.sleep(0.1)
    print("H     H    H    H    H    H     H     H    H    H     H    H    H  ")
    time.sleep(0.1)
    print("  ()                                                      ()       ")
    time.sleep(0.1)
    print(" (  )                                                    (  )")
    time.sleep(0.1)
    print("(    )                                                  (    )")
    time.sleep(0.1)
    print("------                                                  ------")
    time.sleep(0.1)
    print("  ||                                                      ||")
    time.sleep(0.1)
    print(" (_)                                                      (_)")
    time.sleep(0.1)
    print("(00000000000000000)                                            ")
    time.sleep(0.1)
    print("0  0  0  0  0  0  0)                                            ")
    time.sleep(0.1)
    print("  0  0  0  0  0  0 0)------------------                          ")
    time.sleep(0.1)
    print("--------------------H)               \ \                          ")
    time.sleep(0.1)
    print("0  0  0  0  0  0  0 0)                | |                         ")
    time.sleep(0.1)
    print("0  0  0  0  0  0  0 0)                | |                         ")
    time.sleep(0.1)
    print("0  0  0  0  0  0  0 0)                | |                         ")
    time.sleep(0.1)
    print("--------------------H)                | |                         ")
    time.sleep(0.1)
    print(" 0  0  0  0  0  0  0)                 | |                         ")
    time.sleep(0.1)
    print("0  0  0  0  0  0  0)                  | |                         ")
    time.sleep(0.1)
    print("(00000000000000000)___________________|_|                         ")
    time.sleep(0.1)
    print("HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print()
    time.sleep(0.1)
    print("DO YOU WANT TO GO IN TO THE HOLL? OR, YOU GONNA STAY?")
    time.sleep(0.1)
    print("GO INTO THE HOLL")
    time.sleep(0.1)
    print("STAY")
    time.sleep(0.1)
    print()
    choose2 = input("CHOOSE YOUR OPTION(BY TYPING): ")
    time.sleep(0.4)

    if choose2 == "GO INTO THE HOLL":
        GO_INTO_THE_HOLE()
    elif choose2 == "STAY":
        STAY()
    else:
        os.system('clear')
        print("YOU TIPED WRONG OPTION, PLEASE TRY AGAIN!")
        time.sleep(2)
        TAKE_THE_BOX_FROM_MY_WAY()

def GO_INTO_THE_HOLE():
    os.system('clear')
    time.sleep(0.1)
    print("H H H HHHHH HHHHHHHHHHHH H HHHH HHH HH H HHHHHH HHHHH H HHHH HHHHH")
    time.sleep(0.1)
    print("")
    time.sleep(0.1)
    print("")
    time.sleep(0.1)
    print("           _________________________________________")
    time.sleep(0.1)
    print("          /                                         \ ") 
    time.sleep(0.1)
    print("         |    ___________________________________    |")
    time.sleep(0.1)
    print("         |   / _________________________________ \   |")
    time.sleep(0.1)
    print("         |  |  |                               |  |  |")
    time.sleep(0.1)
    print("         |  |  |                               |  |  |")
    time.sleep(0.1)
    print("         |  |  |                               |  |  |")
    time.sleep(0.1)
    print("         |  |  |                               |  |  |")
    time.sleep(0.1)
    print("         |  |  |                               |  |  |")
    time.sleep(0.1)
    print("         |  |  |                               |  |  |")
    time.sleep(0.1)
    print("         |  |  |                               |  |  |")
    time.sleep(0.1)
    print("         |  |  |                               |  |  |")
    time.sleep(0.1)
    print("         |  |  |                               |  |  |")
    time.sleep(0.1)
    print("         |  |   \_____________________________/   |  |")
    time.sleep(0.1)
    print("         |   \___________________________________/   |")
    time.sleep(0.1)
    print("          \_________________________________________/")
    time.sleep(0.1)
    print("HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print()
    time.sleep(0.1)
    print("YOU GOES INTO THE HOLL, DO YOU WANT TO CONTINUE OR, YOU WANT TO BACK?")
    time.sleep(0.1)
    print("CONTINUE")
    time.sleep(0.1)
    print("GO BACK")
    time.sleep(0.1)
    print()
    choose6 = input("CHOOSE YOUR OPTION(BY TYPING): ")
    time.sleep(0.4)

    if choose6 == "CONTINUE":
        CONTINUE_TO_HOLL()
    elif choose6 == "GO BACK":
        TAKE_THE_BOX_FROM_MY_WAY()
    else:
        os.system('clear')
        print("YOU TIPED WRONG OPTION, PLEASE TRY AGAIN!")
        time.sleep(2)
        GO_INTO_THE_HOLE()

def STAY():
    os.system('clear')
    time.sleep(0.1)
    print("HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print("")
    time.sleep(0.1)
    print("          00")
    time.sleep(0.1)
    print("        00  00")
    time.sleep(0.1)
    print("      00      00")
    time.sleep(0.1)
    print("    00          00")
    time.sleep(0.1)
    print("  00              00")
    time.sleep(0.1)
    print(" 00                 00")
    time.sleep(0.1)
    print("0                     00")
    time.sleep(0.1)
    print("                        008")
    time.sleep(0.1)
    print("                          00")
    time.sleep(0.1)
    print("                         88800")
    time.sleep(0.1)
    print("                        88888800")
    time.sleep(0.1)
    print("                        8888888")
    time.sleep(0.1)
    print("                         88888888")
    time.sleep(0.1)
    print("                        0088888888")
    time.sleep(0.1)
    print("                      00   88888888")
    time.sleep(0.1)
    print("                    00    88888888888")
    time.sleep(0.1)
    print("                  00     88888888888888")
    time.sleep(0.1)
    print("                00     888888888888888888")
    time.sleep(0.1)
    print("HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print()
    time.sleep(0.1)
    print("""YOUR FRIEND PUT A PAPER ON THE GROUND, DO YOU WANT TO TURN ON THE TOURCH
AND READ?""")
    time.sleep(0.1)
    print("TURN ON THE TOURCH")
    time.sleep(0.1)
    print("LEAVE IT")
    time.sleep(0.1)
    print()
    choose3 = input("CHOOSE YOUR OPTION(BY TYPING): ")
    time.sleep(0.4)

    if choose3 == "TURN ON THE TOURCH":
        TURN_ON_THE_TOURCH()
    elif choose3 == "LEAVE IT":
        TAKE_THE_BOX_FROM_MY_WAY()
    else:
        os.system('clear')
        print("YOU TIPED WRONG OPTION, PLEASE TRY AGAIN!")
        time.sleep(2)
        STAY()

def CONTINUE_TO_HOLL():
    os.system('clear')
    time.sleep(0.1)
    print("HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print("")
    time.sleep(0.1)
    print("          00")
    time.sleep(0.1)
    print("        00  00")
    time.sleep(0.1)
    print("      00      00")
    time.sleep(0.1)
    print("    00          00")
    time.sleep(0.1)
    print("  00              00")
    time.sleep(0.1)
    print(" 00                 00")
    time.sleep(0.1)
    print("0                     00")
    time.sleep(0.1)
    print("                        008")
    time.sleep(0.1)
    print("                          00")
    time.sleep(0.1)
    print("                         88800")
    time.sleep(0.1)
    print("                        88888800")
    time.sleep(0.1)
    print("                        8888888")
    time.sleep(0.1)
    print("                         88888888")
    time.sleep(0.1)
    print("                        0088888888")
    time.sleep(0.1)
    print("                      00   88888888")
    time.sleep(0.1)
    print("                    00    88888888888")
    time.sleep(0.1)
    print("                  00     88888888888888")
    time.sleep(0.1)
    print("                00     888888888888888888")
    time.sleep(0.1)
    print("HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print()
    time.sleep(0.1)
    print("YOU SEE A PAPER AND GET IT, BUT YOU DON'T HAVE ANY LIGHT OR TORCH, DO YOU WANT TO CONTINUE?")
    time.sleep(0.1)
    print("CONTINUE")
    time.sleep(0.1)
    print("GO BACK")
    time.sleep(0.1)
    print()
    choose7 = input("CHOOSE YOUR OPTION(BY TYPING): ")

    if choose7 == "CONTINUE":
        GOING_TO_BE_FREE()
    elif choose7 == "GO BACK":
        GO_INTO_THE_HOLE()
    else:
        os.system('clear')
        print("YOU TIPED WRONG OPTION, PLEASE TRY AGAIN!")
        time.sleep(2)
        CONTINUE_TO_HOLL()
    
def TURN_ON_THE_TOURCH():
    os.system('clear')
    time.sleep(0.1)
    print("HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print("")
    time.sleep(0.1)
    print("          00")
    time.sleep(0.1)
    print("        00  00")
    time.sleep(0.1)
    print("      00      00")
    time.sleep(0.1)
    print("    00          00")
    time.sleep(0.1)
    print("  00             00")
    time.sleep(0.1)
    print(" 00 " + color.white + "DO" + color.blue + "             00")
    time.sleep(0.1)
    print("0   " + color.white + "YOU" + color.blue + "              00")
    time.sleep(0.1)
    print("    " + color.white + "REALLY" + color.blue + "             00")
    time.sleep(0.1)
    print("      " + color.white + "RUN" + color.blue + "                00")
    time.sleep(0.1)
    print("       " + color.white + "AWAY" + color.blue + "               00")
    time.sleep(0.1)
    print("        " + color.white + "FROM" + color.blue + "                00")
    time.sleep(0.1)
    print("          " + color.white + "HERE" + color.blue + "               00")
    time.sleep(0.1)
    print("            " + color.white + "WITH" + color.blue + "          00  " + color.orange + "( )" + color.blue + "                ")
    time.sleep(0.1)
    print("              " + color.white + "OUT" + color.blue + "       00   " + color.orange + "(   )" + color.blue + "                  ")
    time.sleep(0.1)
    print("               " + color.white + "ME?" + color.blue + "    00    " + color.orange + "(88888)" + color.blue + "                 ")
    time.sleep(0.1)
    print("                    00      " + color.orange + "(88888)" + color.blue + "               ")
    time.sleep(0.1)
    print("                  00          " + color.orange + "(88)" + color.blue + "               ")
    time.sleep(0.1)
    print("                00              88               ")
    time.sleep(0.1)
    print("HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print()
    time.sleep(0.1)
    print("NOW DO YOU WANT TO STAY WITH YOUR FRIEND? OR, YOU GONNA RUN AWAY FROM HERE?")
    time.sleep(0.1)
    print("STAY WITH MY FRIEND")
    time.sleep(0.1)
    print("RUN AWAY FROM HERE")
    time.sleep(0.1)
    print()
    choose4 = input("CHOOSE YOUR OPTION(BY TYPING): ")
    time.sleep(0.4)

    if choose4 == "STAY WITH MY FRIEND":
        STAY_WITH_MY_FRIEND()
    elif choose4 == "RUN AWAY FROM HERE":
        RUN_AWAY_FROM_HERE()
    else:
        os.system('clear')
        print("YOU TIPED WRONG OPTION, PLEASE TRY AGAIN!")
        time.sleep(2)
        TURN_ON_THE_TOURCH

def GOING_TO_BE_FREE():
    os.system('clear')
    time.sleep(0.1)
    print("H                    H               H                 H         H")
    time.sleep(0.1)
    print("")
    time.sleep(0.1)
    print("       ________________________________________________")
    time.sleep(0.1)
    print("      /                                                \ ")
    time.sleep(0.1)
    print("     | " + color.white + "000000000000000000000000000000000000000000000000" + color.blue + " |")
    time.sleep(0.1)
    print("     | " + color.white + "000000000000000000000000000000000000000000000000" + color.blue + " |")
    time.sleep(0.1)
    print("     | " + color.white + "000000000000000000000000000000000000000000000000" + color.blue + " |")
    time.sleep(0.1)
    print("     | " + color.white + "000000000000000000000000000000000000000000000000" + color.blue + " |")
    time.sleep(0.1)
    print("     | " + color.white + "000000000000000000000000000000000000000000000000" + color.blue + " |")
    time.sleep(0.1)
    print("     | " + color.white + "000000000000000000000000000000000000000000000000" + color.blue + " |")
    time.sleep(0.1)
    print("     | " + color.white + "000000000000000000000000000000000000000000000000" + color.blue + " |")
    time.sleep(0.1)
    print("     | " + color.white + "000000000000000000000000000000000000000000000000" + color.blue + " |")
    time.sleep(0.1)
    print("     | " + color.white + "000000000000000000000000000000000000000000000000" + color.blue + " |")
    time.sleep(0.1)
    print("     | " + color.white + "000000000000000000000000000000000000000000000000" + color.blue + " |")
    time.sleep(0.1)
    print("     | " + color.white + "000000000000000000000000000000000000000000000000" + color.blue + " |")
    time.sleep(0.1)
    print("     | " + color.white + "000000000000000000000000000000000000000000000000" + color.blue + " |")
    time.sleep(0.1)
    print("     | " + color.white + "000000000000000000000000000000000000000000000000" + color.blue + " |")
    time.sleep(0.1)
    print("     | " + color.white + "000000000000000000000000000000000000000000000000" + color.blue + " |")
    time.sleep(0.1)
    print("      \________________________________________________/")
    time.sleep(0.1)
    print("HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH")
    time.sleep(1)
    YOU_LOST()

def YOU_LOST():
    os.system('clear')
    time.sleep(0.1)
    print("HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print("HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print("HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print("HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print("HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print("HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print("HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print("HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print("HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print("HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print("HHHHHHHHHHHHHHH " + color.white + "YOU LOST THE GAME MY FRIEND." + color.blue + " HHHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print("HHHHHHHHHHHHHHHHHHHHHH" + color.white + "YOU DO YOUR WORKS WITHOUT..." + color.blue + "HHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print("HHHHHHHHHHHHHHHHHHHHHHHHHHHHHH" + color.white + "THINKING." + color.blue + "HHHHHHHHHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print("HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print("HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print("HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print("HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print("HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print("HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print()
    print("DO YOU WANT TO THINK ABOUT WHAT YOU TYPE AND PLAY AGAIN?")
    print("YES")
    print("NO")
    print()
    choose8 = input("CHOOSE YOUR OPTION(BY TYPING): ")

    if choose8 == "YES":
        EXIT1()
    elif choose8 == "NO":
        os.system('clear')
        print("THINK ABOUT WHAT YOU TYPED AND COME TO PLAY AGAIN...")
        time.sleep(3)
        exit()
    else:
        os.system('clear')
        print("BAD TYPE.")
        time.sleep(0.5)
        print("EXITING...")
        time.sleep(1)
        exit()

def STAY_WITH_MY_FRIEND():
    os.system('clear')
    time.sleep(0.1)
    print("HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print("HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print("HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print("HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print("HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print("HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print("HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print("HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print("HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print("HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print("HHHHHHHHHHHHH " + color.white + "YOU SUCCSSESFULY ENDED THE GAME" + color.blue + " HHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print("HHHHHHHHHHHHHHHHHHHHHH" + color.white + "I AM PROUD OF YOU" + color.blue + "HHHHHHHHHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print("HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print("HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print("HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print("HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print("HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print("HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print("HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH")
    time.sleep(0.1)
    print()
    choose5 = input("PRESS ENTER TO EXIT")
    os.system('clear')
    exit()



def main():
    while True:
        EXIT1()

if __name__ == "__main__":
    main()